<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Test product catalog</title>
  </head>
  <body>
    <div class="container" style="max-width: 900px; padding: 15px; margin: auto; font-family:monospace;">

      <h1>Product catalog</h1>
      <?php echo $this->getContent(); ?>

      <hr>
      <footer>
        <?php
        echo $this->tag->linkTo(
          '',
          'home'
        ) . ' ';
        echo $this->tag->linkTo(
          'catalog',
          'catalog'
        ) . ' ';
        echo $this->tag->linkTo(
          'add',
          'add'
        ) . ' ';
        ?>
      </footer>
    </div>
  </body>
</html>
